# Template des secrets à configurer sur GitHub
# Ces variables doivent être configurées dans les Settings > Secrets > Actions de votre repository

# Variables pour la base de données de production
POSTGRES_PASSWORD:
  # Description: Mot de passe de la base de données de production
  # Type: string
  # Required: true

SUPABASE_ANON_KEY:
  # Description: Clé anonyme Supabase pour l'accès en lecture
  # Type: string
  # Required: true

SUPABASE_SERVICE_ROLE_KEY:
  # Description: Clé de service Supabase pour les opérations en écriture
  # Type: string
  # Required: true

# Variables pour le déploiement
DEPLOYMENT_ENVIRONMENT:
  # Description: Environnement de déploiement (production/staging)
  # Type: string
  # Required: true

# Variables pour les notifications
SLACK_WEBHOOK_URL:
  # Description: URL du webhook Slack pour les notifications
  # Type: string
  # Required: false
